# Generated by Django 4.1.3 on 2022-12-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='alt_id',
        ),
    ]
