# Generated by Django 4.1.3 on 2022-12-15 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_tc_gen', '0004_document_is_privacypolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Terms and Condition', 'Terms and Condition'), ('Privacy Policy', 'Privacy Policy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_privacypolicy',
            field=models.BooleanField(default=False, verbose_name='Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_termsandcondition',
            field=models.BooleanField(default=False, verbose_name='Terms and Condition'),
        ),
    ]
