# Generated by Django 4.1.3 on 2022-12-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tc_gen', '0005_document_user_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_id',
        ),
    ]
